# Generated by Django 5.0.7 on 2026-04-02 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeExposureParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_description', models.CharField(max_length=255, null=True)),
                ('antenna_description', models.CharField(blank=True, max_length=255, null=True)),
                ('antenna_gain', models.FloatField(blank=True, null=True)),
                ('ground_reflection', models.BooleanField(default=False)),
                ('effective_power', models.FloatField(blank=True, null=True)),
                ('duty_factor', models.FloatField(blank=True, null=True)),
                ('transmit_time', models.FloatField(blank=True, null=True)),
                ('receive_time', models.FloatField(blank=True, null=True)),
                ('frequency_mode', models.IntegerField(blank=True, null=True)),
                ('frequency_position', models.IntegerField(blank=True, null=True)),
                ('frequency', models.FloatField(blank=True, null=True)),
                ('operator_name', models.CharField(max_length=128, null=True)),
                ('call_sign', models.CharField(max_length=128, null=True)),
                ('email', models.EmailField(max_length=128, null=True)),
                ('include_calculations', models.BooleanField(default=True)),
                ('mode_factor', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compute Exposure Parameter',
                'verbose_name_plural': 'Compute Exposure Parameters',
                'db_table': 'compute-exposure-parameter',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DutyFactor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('duty_factor_description', models.CharField(max_length=128, null=True)),
                ('duty_factor', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Duty Factor',
                'verbose_name_plural': 'Mode Duty Factor',
                'db_table': 'duty-factor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TransmitReceiveTime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_period', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Transmit Receive Time',
                'verbose_name_plural': 'Transmit Receive Times',
                'db_table': 'transmit-receive-time',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RFReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Untitled Project', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'RF Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
