# Generated by Django 5.0.7 on 2026-04-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfreport',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'RFReports'},
        ),
    ]
